# Home Assistant Add-on Build Configuration
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-extended-build

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm


labels:
  org.opencontainers.image.title: "Crypto Inspect"
  org.opencontainers.image.description: "Cryptocurrency candlestick data collector"
  org.opencontainers.image.source: "https://github.com/Mesteriis/crypto-inspector"
  org.opencontainers.image.licenses: "MIT"
