"""add candlestick_records table

Revision ID: 7c7ba6464e14
Revises:
Create Date: 2026-01-17 21:37:39.867765

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c7ba6464e14"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candlestick_records",
        sa.Column(
            "exchange",
            sa.String(length=50),
            nullable=False,
            comment="Exchange name (e.g., binance, coinbase, kraken)",
        ),
        sa.Column(
            "symbol",
            sa.String(length=50),
            nullable=False,
            comment="Trading pair symbol (e.g., BTC/USDT)",
        ),
        sa.Column(
            "interval",
            sa.String(length=10),
            nullable=False,
            comment="Candlestick interval (e.g., 1m, 5m, 1h, 1d)",
        ),
        sa.Column(
            "timestamp",
            sa.BigInteger(),
            nullable=False,
            comment="Candle open time as Unix timestamp in milliseconds",
        ),
        sa.Column(
            "open_price",
            sa.Numeric(precision=30, scale=10),
            nullable=False,
            comment="Opening price of the candle",
        ),
        sa.Column(
            "high_price",
            sa.Numeric(precision=30, scale=10),
            nullable=False,
            comment="Highest price during the candle period",
        ),
        sa.Column(
            "low_price",
            sa.Numeric(precision=30, scale=10),
            nullable=False,
            comment="Lowest price during the candle period",
        ),
        sa.Column(
            "close_price",
            sa.Numeric(precision=30, scale=10),
            nullable=False,
            comment="Closing price of the candle",
        ),
        sa.Column(
            "volume",
            sa.Numeric(precision=30, scale=10),
            nullable=False,
            comment="Base asset trading volume",
        ),
        sa.Column(
            "quote_volume",
            sa.Numeric(precision=30, scale=10),
            nullable=True,
            comment="Quote asset volume (e.g., USDT volume)",
        ),
        sa.Column(
            "trades_count",
            sa.BigInteger(),
            nullable=True,
            comment="Number of trades during the candle period",
        ),
        sa.Column(
            "loaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when this record was loaded into the database",
        ),
        sa.Column(
            "fetch_time_ms",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Time taken to fetch this data from exchange in milliseconds",
        ),
        sa.Column(
            "source_raw",
            sa.String(length=1000),
            nullable=True,
            comment="Original raw response from exchange for debugging (JSON string)",
        ),
        sa.Column(
            "is_complete",
            sa.Boolean(),
            nullable=False,
            comment="Whether this candle is complete (closed) or still forming",
        ),
        sa.PrimaryKeyConstraint("exchange", "symbol", "interval", "timestamp"),
        comment="Stores historical candlestick (OHLCV) data from various exchanges",
    )
    op.create_index(
        "ix_candlestick_exchange_symbol_interval",
        "candlestick_records",
        ["exchange", "symbol", "interval"],
        unique=False,
    )
    op.create_index("ix_candlestick_loaded_at", "candlestick_records", ["loaded_at"], unique=False)
    op.create_index("ix_candlestick_symbol", "candlestick_records", ["symbol"], unique=False)
    op.create_index("ix_candlestick_timestamp", "candlestick_records", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_candlestick_timestamp", table_name="candlestick_records")
    op.drop_index("ix_candlestick_symbol", table_name="candlestick_records")
    op.drop_index("ix_candlestick_loaded_at", table_name="candlestick_records")
    op.drop_index("ix_candlestick_exchange_symbol_interval", table_name="candlestick_records")
    op.drop_table("candlestick_records")
    # ### end Alembic commands ###
