"""add_sensor_states_table

Revision ID: 80d9d02135d1
Revises: 201b0d1e8ea9
Create Date: 2026-01-25 13:50:07.008627

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '80d9d02135d1'
down_revision: str | None = '201b0d1e8ea9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_states',
    sa.Column('unique_id', sa.Text(), nullable=False, comment='Unique sensor identifier (e.g., crypto_inspect_prices)'),
    sa.Column('name', sa.Text(), nullable=False, comment='Human-readable sensor name'),
    sa.Column('value', sa.Text(), nullable=False, comment='Sensor value (JSON string for complex values)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_states')
    # ### end Alembic commands ###
